"use client";

import { create } from "zustand";
import { persist } from "zustand/middleware";
import {
  daysUntil, drawOffer, pegState, examConcepts, newConceptState, pickQuestion, readiness, streakMultiplier, updateState,
  type Attempt, type Concept, type ConceptState, type Confidence, type ExamResult, type OptionId, type Question,
} from "./engine";
import { LINES } from "./copy";
import {
  answerMult, betOutcome, calibrationBonus, pegHand, type HandCard, defusePayout, examPotPayout, POT_PER_BOMB, calibrationGap, calibrationGrade, incomeIndex, interest, isPeg, isStudy, MAX_COPIES, priceOf, rerollCost, tierUnlocked,
  type PriceCtx,
} from "./economy";
import { FEVER_BALLS, FEVER_FLAT, type OwnedPeg, type SpecialKind } from "./board";

export type Screen = "setup" | "intro" | "hub" | "draw" | "question" | "reveal" | "board" | "summary" | "shop" | "report" | "settings";
export type SessionKind = "shift" | "defuse" | "exam";
export type ShiftMod = "magnet" | "mega" | "quake";
export type ShopItem = "secondChance" | "defuser" | ShiftMod | SpecialKind;

export const SHIFT_LENGTH = 8;
export const EXAM_LENGTH = 10;
export const START_CHIPS = 5;
/** Pegs renamed by the game-show reskin, for old saves. */
const RENAMED: Record<string, SpecialKind> = { roulette: "wheel", blackjack: "quiz21" };
export const SHIFT_MODS: ShiftMod[] = ["magnet", "mega", "quake"];
export const SPECIALS: SpecialKind[] = ["wheel", "quiz21", "quiz", "splitter", "blackhole", "bumper"];

export interface Unit {
  id: string;
  name: string;
  examDate: string; // YYYY-MM-DD
  live: boolean; // generated by the model rather than the seeded bank
}

export interface Session {
  kind: SessionKind;
  total: number;
  answered: number;
  recent: string[];
  offer: string[];
  plan: string[]; // exam concept order
  conceptId?: string;
  questionId?: string;
  shownAt?: number;
  retrying: boolean;
  eliminated: OptionId[];
  pendingBalls: number;
  pendingChips: number; // the bet payout, paid with the drop
  dropSeed: number;
  chipsEarned: number;
  skillChips: number; // from correct answers and calibration
  chanceChips: number; // from buckets, the wheel and other specials
  debtAdded: number;
  fever?: boolean; // the waiting drop is a Fever round
  hand?: HandCard[]; // this Shift's correct answers, for Peg Hands
  feverChips?: number;
  calBonus?: number; // paid at the end of a Shift
  interest?: number;
  bombsPlanted: string[];
  bombsDefused: string[];
  readinessBefore: number;
  correct: number;
  mult: number; // multiplier of the answer whose drop is waiting (streak, later Peg Hand)
  streakMult?: number; // older saves
  finished?: boolean; // reached the summary
  resume?: Screen; // where to pick up if you left mid-session
}

const PLAY_SCREENS: Screen[] = ["draw", "question", "reveal", "board"];
/** A Shift, Defuser or Exam Day you've started but not finished (you may have wandered off to the Shop). */
export const inProgress = (session: Session | null): session is Session => Boolean(session && !session.finished);

export interface Reveal {
  questionId: string;
  conceptId: string;
  chosen: OptionId;
  confidence: Confidence;
  correct: boolean;
  balls: number;
  chips: number; // bet payout, before the board
  debt: number; // Ledger debt added
  mult: number;
  bombPlanted: boolean;
  bombDefused: boolean;
  potPaid?: number; // Ledger Pot share paid for this defuse
  fever?: boolean; // that was the last bomb on the board
  bombWaiting?: boolean; // right on a bomb that hasn't waited a Shift yet
  secondChance: boolean;
  line: string;
  streak: number; // correct answers in a row, including this one
  lostStreak: number; // the run a wrong answer just ended
}

export type Skin = "retro" | "chaos";

export interface Settings {
  skin: Skin;
  calm: boolean;
  dailyCap: number;
  sound: boolean;
  reducedMotion: boolean;
}

interface Data {
  unit: Unit | null;
  concepts: Concept[];
  questions: Question[];
  conceptState: Record<string, ConceptState>;
  attempts: Attempt[];
  chips: number;
  debt: number; // Ledger debt: no floor, never comes out of chips
  pot: number; // Ledger Pot: +5 per bomb planted, paid out by defusing and on Exam Day
  bombLedger: Record<string, BombEntry>;
  armed: string[]; // bomb concepts a ball hit: their retest leads the next Draw
  inventory: { secondChance: number; magnet: boolean; mega: boolean; quake: boolean; pegs: OwnedPeg[] };
  shop: ShopState;
  settings: Settings;
  shiftsDone: number;
  shiftLog: { date: string; count: number };
  flagged: string[];
  exam: ExamResult | null;
  streak: number;
  screen: Screen;
  session: Session | null;
  reveal: Reveal | null;
  line: string;
}

/** A planted bomb's share of the pot, and when and where it was planted. */
export interface BombEntry {
  share: number;
  shift: number; // shiftsDone when planted; defusable once a later Shift starts
  questionId: string;
}

export interface ShopState {
  boughtThisRun: Partial<Record<ShopItem, number>>;
  usesThisShift: Partial<Record<ShopItem, number>>;
  rerolls: number; // this Shift
  shiftIncome: number[]; // chips earned per finished Shift, for the income index
}

interface Actions {
  reroll(): void;
  setup(unit: Unit, concepts: Concept[], questions: Question[]): void;
  go(screen: Screen): void;
  startShift(): void;
  resume(): void;
  startExam(): void;
  choose(conceptId: string): void;
  answer(chosen: OptionId, confidence: Confidence): void;
  continueReveal(): void;
  finishDrop(chips: number, skill?: number, armed?: string[], feverFlat?: boolean): void;
  buy(item: ShopItem, conceptId?: string): void;
  flag(questionId: string): void;
  updateSettings(s: Partial<Settings>): void;
  reset(): void;
}

const today = () => new Date().toISOString().slice(0, 10);

const initial: Data = {
  unit: null,
  concepts: [],
  questions: [],
  conceptState: {},
  attempts: [],
  chips: START_CHIPS,
  debt: 0,
  pot: 0,
  bombLedger: {},
  armed: [],
  inventory: { secondChance: 0, magnet: false, mega: false, quake: false, pegs: [] },
  shop: { boughtThisRun: {}, usesThisShift: {}, rerolls: 0, shiftIncome: [] },
  settings: { skin: "retro", calm: false, dailyCap: 6, sound: true, reducedMotion: false },
  shiftsDone: 0,
  shiftLog: { date: "", count: 0 },
  flagged: [],
  exam: null,
  streak: 0,
  screen: "setup",
  session: null,
  reveal: null,
  line: "",
};

export const useGame = create<Data & Actions>()(
  persist(
    (set, get) => {
      const days = () => daysUntil(get().unit?.examDate ?? today());
      const states = () => get().concepts.map((c) => get().conceptState[c.id]);
      const ready = () => readiness(states(), get().exam);

      const newSession = (kind: SessionKind, total: number, plan: string[] = []): Session => ({
        kind, total, plan, answered: 0, recent: [], offer: [], retrying: false, eliminated: [], pendingBalls: 0, pendingChips: 0,
        dropSeed: 0, chipsEarned: 0, skillChips: 0, chanceChips: 0, debtAdded: 0, bombsPlanted: [], bombsDefused: [], readinessBefore: ready(), correct: 0, mult: 1,
      });

      const showDraw = (session: Session) => {
        const offer = drawOffer(states(), session.recent, days(), get().attempts.length);
        // a bomb peg a ball hit arms its retest: it takes the last slot unless it was just asked
        const armed = get().armed.find((c) => get().conceptState[c]?.bombActive && !offer.includes(c) && !session.recent.slice(-2).includes(c));
        if (armed) offer[offer.length - 1] = armed;
        set({ session: { ...session, offer }, screen: "draw" });
      };

      const endSession = (session: Session) => {
        if (session.kind === "exam") {
          const exam = { correct: session.correct, total: session.answered, at: new Date().toISOString() };
          set((s) => {
            // Exam Day pays out the rest of the pot by readiness, settled against debt
            const earned = s.shop.shiftIncome.reduce((a, b) => a + b, 0);
            const potPaid = examPotPayout(s.pot, readiness(states(), exam), earned, s.debt);
            return { exam: { ...exam, potPaid, debt: s.debt, earned }, chips: s.chips + potPaid, pot: 0, bombLedger: {}, session: null, screen: "report" };
          });
          return;
        }
        const drop = Math.max(0, ready() - session.readinessBefore);
        // calibration pays: a Shift ends with 3 chips per calibration grade point (last 20 answers)
        const calBonus = session.kind === "shift" ? calibrationBonus(calibrationGrade(calibrationGap(get().attempts))) : 0;
        const shift = session.kind === "shift";
        set((s) => {
          // interest: +1 per 10 chips held at the end of a Shift, capped at +3
          const paid = shift ? interest(s.chips + calBonus) : 0;
          return {
            chips: s.chips + calBonus + paid,
            session: { ...session, finished: true, calBonus, interest: paid, skillChips: (session.skillChips ?? 0) + calBonus, chipsEarned: session.chipsEarned + calBonus },
            screen: "summary",
            line: LINES.endShift(drop),
            shiftsDone: s.shiftsDone + (shift ? 1 : 0),
            inventory: shift ? { ...s.inventory, magnet: false, mega: false, quake: false } : s.inventory,
            shop: shift ? { ...s.shop, usesThisShift: {}, rerolls: 0, shiftIncome: [...s.shop.shiftIncome, session.chipsEarned + calBonus] } : s.shop,
          };
        });
      };

      const next = (session: Session) => {
        if (session.answered >= session.total) return endSession(session);
        if (session.kind === "exam") {
          set({ session });
          return get().choose(session.plan[session.answered]);
        }
        showDraw(session);
      };

      return {
        ...initial,

        setup(unit, concepts, questions) {
          const now = new Date();
          set({
            ...initial,
            settings: get().settings,
            unit,
            concepts,
            questions,
            conceptState: Object.fromEntries(concepts.map((c) => [c.id, newConceptState(c.id, now)])),
            screen: "intro",
            line: LINES.setup(unit.name, daysUntil(unit.examDate)),
          });
        },

        go(screen) {
          const { session, screen: from } = get();
          // leaving mid-session (to the Hub, Shop, Report...) bookmarks where you were
          if (inProgress(session) && PLAY_SCREENS.includes(from) && !PLAY_SCREENS.includes(screen)) set({ session: { ...session, resume: from } });
          set({ screen });
        },

        resume() {
          const { session } = get();
          if (!inProgress(session)) return;
          const at = session.resume ?? "draw";
          set({ screen: at === "board" ? "reveal" : at, session: { ...session, resume: undefined, shownAt: at === "question" ? Date.now() : session.shownAt } });
        },

        startShift() {
          if (inProgress(get().session)) return get().resume(); // pick up the Shift you left
          const { shiftLog, settings } = get();
          const log = shiftLog.date === today() ? shiftLog : { date: today(), count: 0 };
          if (log.count >= settings.dailyCap) {
            set({ line: LINES.cap, screen: "hub" });
            return;
          }
          set({ shiftLog: { ...log, count: log.count + 1 }, reveal: null });
          showDraw(newSession("shift", SHIFT_LENGTH));
        },

        startExam() {
          if (inProgress(get().session)) return get().resume();
          const plan = examConcepts(states(), EXAM_LENGTH, get().attempts.length + 7);
          set({ session: newSession("exam", plan.length, plan), line: LINES.exam, reveal: null });
          get().choose(plan[0]);
        },

        choose(conceptId) {
          const { questions, attempts, flagged, session } = get();
          if (!session) return;
          const q = pickQuestion(questions, conceptId, attempts, flagged);
          if (!q) {
            // every question on this concept was flagged; skip it
            return next({ ...session, total: Math.max(session.answered, session.total - 1) });
          }
          set({ session: { ...session, conceptId, questionId: q.id, shownAt: Date.now(), eliminated: [], retrying: false }, screen: "question" });
        },

        answer(chosen, confidence) {
          const s = get();
          const session = s.session;
          const q = s.questions.find((x) => x.id === session?.questionId);
          if (!session || !q) return;
          const correct = chosen === q.correct;
          const now = new Date();
          const attempt: Attempt = {
            id: `${now.getTime()}-${s.attempts.length}`, questionId: q.id, conceptId: q.conceptId, chosen, confidence, correct,
            ms: Date.now() - (session.shownAt ?? Date.now()), at: now.toISOString(), exam: session.kind === "exam",
          };
          const base = { questionId: q.id, conceptId: q.conceptId, chosen, confidence, correct };

          if (!correct && s.inventory.secondChance > 0 && !session.retrying && session.kind !== "exam") {
            set({
              attempts: [...s.attempts, attempt],
              inventory: { ...s.inventory, secondChance: s.inventory.secondChance - 1 },
              session: { ...session, retrying: true, eliminated: [...session.eliminated, chosen] },
              reveal: { ...base, balls: 0, chips: 0, debt: 0, mult: 1, bombPlanted: false, bombDefused: false, secondChance: true, line: LINES.secondChance, streak: s.streak, lostStreak: 0 },
              screen: "reveal",
            });
            return;
          }

          const exam = session.kind === "exam";
          // the multiplier you're playing at scales the gain if right and the debt if wrong, so honest bets stay best
          const cards = session.hand ?? [];
          const mult = exam ? 1 : answerMult(streakMultiplier(s.streak + 1), pegHand(cards, s.concepts.length));
          const index = s.concepts.findIndex((c) => c.id === q.conceptId);
          const out = exam ? { chips: 0, debt: 0, balls: 0, plantBomb: betOutcome(confidence, correct).plantBomb } : betOutcome(confidence, correct, mult);
          const streak = exam ? s.streak : correct ? s.streak + 1 : 0; // Exam Day doesn't touch the streak
          const before = s.conceptState[q.conceptId];
          const planted = s.bombLedger[q.conceptId];
          // a bomb defuses on a different question, at least one Shift after it was planted
          const defusable = !planted || (s.shiftsDone > planted.shift && planted.questionId !== q.id);
          const after = updateState(before, { confidence, correct, defusable }, days(), now);
          const bombDefused = before.bombActive && !after.bombActive;
          const fever = bombDefused && !exam && s.concepts.every((c) => c.id === q.conceptId || !s.conceptState[c.id]?.bombActive);
          const bombWaiting = before.bombActive && after.bombActive && correct && confidence !== "guess" && !defusable;
          const potPaid = bombDefused && planted ? defusePayout(planted.share) : 0;
          const bombLedger = { ...s.bombLedger };
          if (bombDefused) delete bombLedger[q.conceptId];
          if (out.plantBomb) bombLedger[q.conceptId] = { share: (planted?.share ?? 0) + POT_PER_BOMB, shift: s.shiftsDone, questionId: q.id };
          const line = out.plantBomb
            ? LINES.certainWrong
            : bombDefused
              ? LINES.bombDefused(potPaid)
              : bombWaiting
                ? LINES.bombWaiting
              : correct
                ? { guess: LINES.guessRight, pretty: LINES.prettyRight, certain: LINES.certainRight }[confidence]
                : confidence === "guess" ? LINES.guessWrong : LINES.prettyWrong;

          set({
            attempts: [...s.attempts, attempt],
            conceptState: { ...s.conceptState, [q.conceptId]: after },
            debt: s.debt + out.debt,
            pot: s.pot - potPaid + (out.plantBomb ? POT_PER_BOMB : 0),
            chips: s.chips + potPaid,
            bombLedger,
            armed: s.armed.filter((c) => c !== q.conceptId),
            streak,
            reveal: { ...base, balls: out.balls, chips: out.chips, debt: out.debt, mult, bombPlanted: out.plantBomb, bombDefused, potPaid, bombWaiting, fever, secondChance: false, line, streak, lostStreak: !exam && !correct ? s.streak : 0 },
            session: {
              ...session,
              answered: session.answered + 1,
              recent: [...session.recent, q.conceptId],
              retrying: false,
              eliminated: [],
              pendingBalls: out.balls + (fever ? FEVER_BALLS : 0),
              hand: correct && !exam && index >= 0 ? [...cards, { index, confidence }] : cards,
              fever,
              pendingChips: out.chips,
              dropSeed: s.attempts.length + 1,
              mult,
              debtAdded: (session.debtAdded ?? 0) + out.debt,
              skillChips: (session.skillChips ?? 0) + potPaid, // defusing is knowledge
              chipsEarned: session.chipsEarned + potPaid,
              correct: session.correct + (correct ? 1 : 0),
              bombsPlanted: out.plantBomb ? [...session.bombsPlanted, q.conceptId] : session.bombsPlanted,
              bombsDefused: bombDefused ? [...session.bombsDefused, q.conceptId] : session.bombsDefused,
            },
            screen: "reveal",
          });
        },

        continueReveal() {
          const { reveal, session } = get();
          if (!session || !reveal) return;
          if (reveal.secondChance) return set({ screen: "question", reveal: null, session: { ...session, shownAt: Date.now() } });
          if (session.kind === "exam") return next(session);
          // Shift and Defuser answers drop on the board beside the reveal; finishDrop moves on
        },

        finishDrop(raw, rawSkill = 0, armed = [], feverFlat = false) {
          const { session } = get();
          if (!session) return;
          // Calm mode and reduced motion: Fever is a plain summary paying its expected value
          if (feverFlat && session.fever) raw += FEVER_FLAT;
          if (armed.length) set((s) => ({ armed: [...new Set([...s.armed, ...armed])] }));
          // the multiplier rewards knowing, so it scales the bet payout (already in pendingChips) but never the board's luck
          const board = Math.round(raw);
          const boardSkill = Math.min(board, Math.round(rawSkill)); // popup questions answered right
          const answer = session.pendingChips ?? 0;
          set((s) => ({ chips: s.chips + answer + board }));
          next({
            ...session,
            pendingBalls: 0,
            pendingChips: 0,
            mult: 1,
            fever: false,
            chipsEarned: session.chipsEarned + answer + board,
            skillChips: (session.skillChips ?? 0) + answer + boardSkill,
            chanceChips: (session.chanceChips ?? 0) + board - boardSkill,
          });
        },

        buy(item, conceptId) {
          const s = get();
          const ctx = priceCtx(s);
          const { price } = priceOf(item, ctx);
          if (s.chips < price) return;
          const counted = (patch: Partial<Data>) =>
            set({
              ...patch,
              chips: s.chips - price,
              shop: {
                ...s.shop,
                boughtThisRun: { ...s.shop.boughtThisRun, [item]: (s.shop.boughtThisRun[item] ?? 0) + 1 },
                usesThisShift: isStudy(item) ? { ...s.shop.usesThisShift, [item]: (s.shop.usesThisShift[item] ?? 0) + 1 } : s.shop.usesThisShift,
              },
            });
          if (item === "secondChance") counted({ inventory: { ...s.inventory, secondChance: s.inventory.secondChance + 1 } });
          if ((SHIFT_MODS as ShopItem[]).includes(item) && !s.inventory[item as ShiftMod]) counted({ inventory: { ...s.inventory, [item]: true } });
          if (isPeg(item) && ctx.copies[item]! < MAX_COPIES) counted({ inventory: { ...s.inventory, pegs: [...s.inventory.pegs, { kind: item, tier: ctx.tier }] } });
          if (item === "defuser" && conceptId && s.conceptState[conceptId]?.bombActive && !inProgress(s.session)) {
            counted({ session: newSession("defuse", 1), reveal: null });
            get().choose(conceptId);
          }
        },

        reroll() {
          const s = get();
          const cost = rerollCost(s.shop.rerolls);
          if (s.chips < cost) return;
          set({ chips: s.chips - cost, shop: { ...s.shop, rerolls: s.shop.rerolls + 1 } });
        },

        flag(questionId) {
          const { session } = get();
          set((s) => ({ flagged: s.flagged.includes(questionId) ? s.flagged : [...s.flagged, questionId] }));
          if (session?.questionId === questionId && session.conceptId) get().choose(session.conceptId);
        },

        updateSettings(patch) {
          set((s) => ({ settings: { ...s.settings, ...patch } }));
        },

        reset() {
          set({ ...initial, settings: get().settings });
        },
      };
    },
    {
      name: "sure-thing-v1",
      merge: (saved, current) => mergeSave(saved, current),
    }
  )
);


/** Loads older sure-thing-v1 saves with sensible defaults. They predate the crazy shop, the game-show reskin, copies and tiers. */
export function mergeSave<T extends Data>(saved: unknown, current: T): T {
  const s = (saved ?? {}) as Partial<Data>;
  const inventory = { ...initial.inventory, ...s.inventory };
  // pegs were plain names before copies and tiers
  inventory.pegs = (inventory.pegs as (OwnedPeg | string)[]).map((k) => (typeof k === "string" ? { kind: RENAMED[k] ?? (k as SpecialKind), tier: 1 } : k));
  const shop = { ...initial.shop, ...s.shop };
  return { ...current, ...s, inventory, shop, settings: { ...initial.settings, ...s.settings } };
}

/** Share of concepts that are Solid (box 4 or 5, no bomb). Unlocks stronger peg tiers. */
export function masteredShare(s: Pick<Data, "concepts" | "conceptState">) {
  if (s.concepts.length === 0) return 0;
  return s.concepts.filter((c) => pegState(s.conceptState[c.id]) === "solid").length / s.concepts.length;
}

export function priceCtx(s: Pick<Data, "concepts" | "conceptState" | "inventory" | "shop">): PriceCtx {
  const copies: Partial<Record<SpecialKind, number>> = Object.fromEntries(SPECIALS.map((k) => [k, s.inventory.pegs.filter((p) => p.kind === k).length]));
  return { boughtThisRun: s.shop.boughtThisRun, usesThisShift: s.shop.usesThisShift, copies, tier: tierUnlocked(masteredShare(s)), index: incomeIndex(s.shop.shiftIncome) };
}

/** Shared derived values for the UI. */
export function useDerived() {
  const g = useGame();
  const states = g.concepts.map((c) => g.conceptState[c.id]).filter(Boolean);
  const days = daysUntil(g.unit?.examDate ?? today());
  const ready = readiness(states, g.exam);
  return { states, days, ready, debt: 100 - ready, bombs: states.filter((s) => s.bombActive).map((s) => s.conceptId) };
}
