"use client";

import { create } from "zustand";
import { persist } from "zustand/middleware";
import {
  betOutcome, daysUntil, drawOffer, examConcepts, newConceptState, pickQuestion, readiness, streakMultiplier, updateState,
  type Attempt, type Concept, type ConceptState, type Confidence, type ExamResult, type OptionId, type Question,
} from "./engine";
import { LINES } from "./copy";
import type { SpecialKind } from "./board";

export type Screen = "setup" | "intro" | "hub" | "draw" | "question" | "reveal" | "board" | "summary" | "shop" | "report" | "settings";
export type SessionKind = "shift" | "defuse" | "exam";
export type ShiftMod = "magnet" | "mega" | "quake";
export type ShopItem = "secondChance" | "defuser" | ShiftMod | SpecialKind;

export const SHIFT_LENGTH = 8;
export const EXAM_LENGTH = 10;
export const START_CHIPS = 5;
export const PRICES: Record<ShopItem, number> = {
  secondChance: 8, defuser: 10, magnet: 15, mega: 22, quake: 6,
  wheel: 18, quiz21: 20, quiz: 12, splitter: 14, blackhole: 16, bumper: 8,
};
/** Pegs renamed by the game-show reskin, for old saves. */
const RENAMED: Record<string, SpecialKind> = { roulette: "wheel", blackjack: "quiz21" };
export const SHIFT_MODS: ShiftMod[] = ["magnet", "mega", "quake"];
export const SPECIALS: SpecialKind[] = ["wheel", "quiz21", "quiz", "splitter", "blackhole", "bumper"];

export interface Unit {
  id: string;
  name: string;
  examDate: string; // YYYY-MM-DD
  live: boolean; // generated by the model rather than the seeded bank
}

export interface Session {
  kind: SessionKind;
  total: number;
  answered: number;
  recent: string[];
  offer: string[];
  plan: string[]; // exam concept order
  conceptId?: string;
  questionId?: string;
  shownAt?: number;
  retrying: boolean;
  eliminated: OptionId[];
  pendingBalls: number;
  dropSeed: number;
  chipsEarned: number;
  chipsLost: number;
  bombsPlanted: string[];
  bombsDefused: string[];
  readinessBefore: number;
  correct: number;
  streakMult: number; // chip multiplier earned by the answer whose balls are waiting to drop
  finished?: boolean; // reached the summary
  resume?: Screen; // where to pick up if you left mid-session
}

const PLAY_SCREENS: Screen[] = ["draw", "question", "reveal", "board"];
/** A Shift, Defuser or Exam Day you've started but not finished (you may have wandered off to the Shop). */
export const inProgress = (session: Session | null): session is Session => Boolean(session && !session.finished);

export interface Reveal {
  questionId: string;
  conceptId: string;
  chosen: OptionId;
  confidence: Confidence;
  correct: boolean;
  balls: number;
  chipPenalty: number;
  bombPlanted: boolean;
  bombDefused: boolean;
  secondChance: boolean;
  line: string;
  streak: number; // correct answers in a row, including this one
  lostStreak: number; // the run a wrong answer just ended
}

export type Skin = "retro" | "chaos";

export interface Settings {
  skin: Skin;
  calm: boolean;
  dailyCap: number;
  sound: boolean;
  reducedMotion: boolean;
}

interface Data {
  unit: Unit | null;
  concepts: Concept[];
  questions: Question[];
  conceptState: Record<string, ConceptState>;
  attempts: Attempt[];
  chips: number;
  inventory: { secondChance: number; magnet: boolean; mega: boolean; quake: boolean; pegs: SpecialKind[] };
  settings: Settings;
  shiftsDone: number;
  shiftLog: { date: string; count: number };
  flagged: string[];
  exam: ExamResult | null;
  streak: number;
  screen: Screen;
  session: Session | null;
  reveal: Reveal | null;
  line: string;
}

interface Actions {
  setup(unit: Unit, concepts: Concept[], questions: Question[]): void;
  go(screen: Screen): void;
  startShift(): void;
  resume(): void;
  startExam(): void;
  choose(conceptId: string): void;
  answer(chosen: OptionId, confidence: Confidence): void;
  continueReveal(): void;
  finishDrop(chips: number): void;
  buy(item: ShopItem, conceptId?: string): void;
  flag(questionId: string): void;
  updateSettings(s: Partial<Settings>): void;
  reset(): void;
}

const today = () => new Date().toISOString().slice(0, 10);

const initial: Data = {
  unit: null,
  concepts: [],
  questions: [],
  conceptState: {},
  attempts: [],
  chips: START_CHIPS,
  inventory: { secondChance: 0, magnet: false, mega: false, quake: false, pegs: [] },
  settings: { skin: "retro", calm: false, dailyCap: 6, sound: true, reducedMotion: false },
  shiftsDone: 0,
  shiftLog: { date: "", count: 0 },
  flagged: [],
  exam: null,
  streak: 0,
  screen: "setup",
  session: null,
  reveal: null,
  line: "",
};

export const useGame = create<Data & Actions>()(
  persist(
    (set, get) => {
      const days = () => daysUntil(get().unit?.examDate ?? today());
      const states = () => get().concepts.map((c) => get().conceptState[c.id]);
      const ready = () => readiness(states(), get().exam);

      const newSession = (kind: SessionKind, total: number, plan: string[] = []): Session => ({
        kind, total, plan, answered: 0, recent: [], offer: [], retrying: false, eliminated: [], pendingBalls: 0,
        dropSeed: 0, chipsEarned: 0, chipsLost: 0, bombsPlanted: [], bombsDefused: [], readinessBefore: ready(), correct: 0, streakMult: 1,
      });

      const showDraw = (session: Session) => {
        const offer = drawOffer(states(), session.recent, days(), get().attempts.length);
        set({ session: { ...session, offer }, screen: "draw" });
      };

      const endSession = (session: Session) => {
        if (session.kind === "exam") {
          set({ exam: { correct: session.correct, total: session.answered, at: new Date().toISOString() }, session: null, screen: "report" });
          return;
        }
        const drop = Math.max(0, ready() - session.readinessBefore);
        set((s) => ({
          session: { ...session, finished: true },
          screen: "summary",
          line: LINES.endShift(drop),
          shiftsDone: s.shiftsDone + (session.kind === "shift" ? 1 : 0),
          inventory: session.kind === "shift" ? { ...s.inventory, magnet: false, mega: false, quake: false } : s.inventory,
        }));
      };

      const next = (session: Session) => {
        if (session.answered >= session.total) return endSession(session);
        if (session.kind === "exam") {
          set({ session });
          return get().choose(session.plan[session.answered]);
        }
        showDraw(session);
      };

      return {
        ...initial,

        setup(unit, concepts, questions) {
          const now = new Date();
          set({
            ...initial,
            settings: get().settings,
            unit,
            concepts,
            questions,
            conceptState: Object.fromEntries(concepts.map((c) => [c.id, newConceptState(c.id, now)])),
            screen: "intro",
            line: LINES.setup(unit.name, daysUntil(unit.examDate)),
          });
        },

        go(screen) {
          const { session, screen: from } = get();
          // leaving mid-session (to the Hub, Shop, Report...) bookmarks where you were
          if (inProgress(session) && PLAY_SCREENS.includes(from) && !PLAY_SCREENS.includes(screen)) set({ session: { ...session, resume: from } });
          set({ screen });
        },

        resume() {
          const { session } = get();
          if (!inProgress(session)) return;
          const at = session.resume ?? "draw";
          set({ screen: at === "board" ? "reveal" : at, session: { ...session, resume: undefined, shownAt: at === "question" ? Date.now() : session.shownAt } });
        },

        startShift() {
          if (inProgress(get().session)) return get().resume(); // pick up the Shift you left
          const { shiftLog, settings } = get();
          const log = shiftLog.date === today() ? shiftLog : { date: today(), count: 0 };
          if (log.count >= settings.dailyCap) {
            set({ line: LINES.cap, screen: "hub" });
            return;
          }
          set({ shiftLog: { ...log, count: log.count + 1 }, reveal: null });
          showDraw(newSession("shift", SHIFT_LENGTH));
        },

        startExam() {
          if (inProgress(get().session)) return get().resume();
          const plan = examConcepts(states(), EXAM_LENGTH, get().attempts.length + 7);
          set({ session: newSession("exam", plan.length, plan), line: LINES.exam, reveal: null });
          get().choose(plan[0]);
        },

        choose(conceptId) {
          const { questions, attempts, flagged, session } = get();
          if (!session) return;
          const q = pickQuestion(questions, conceptId, attempts, flagged);
          if (!q) {
            // every question on this concept was flagged; skip it
            return next({ ...session, total: Math.max(session.answered, session.total - 1) });
          }
          set({ session: { ...session, conceptId, questionId: q.id, shownAt: Date.now(), eliminated: [], retrying: false }, screen: "question" });
        },

        answer(chosen, confidence) {
          const s = get();
          const session = s.session;
          const q = s.questions.find((x) => x.id === session?.questionId);
          if (!session || !q) return;
          const correct = chosen === q.correct;
          const now = new Date();
          const attempt: Attempt = {
            id: `${now.getTime()}-${s.attempts.length}`, questionId: q.id, conceptId: q.conceptId, chosen, confidence, correct,
            ms: Date.now() - (session.shownAt ?? Date.now()), at: now.toISOString(), exam: session.kind === "exam",
          };
          const base = { questionId: q.id, conceptId: q.conceptId, chosen, confidence, correct };

          if (!correct && s.inventory.secondChance > 0 && !session.retrying && session.kind !== "exam") {
            set({
              attempts: [...s.attempts, attempt],
              inventory: { ...s.inventory, secondChance: s.inventory.secondChance - 1 },
              session: { ...session, retrying: true, eliminated: [...session.eliminated, chosen] },
              reveal: { ...base, balls: 0, chipPenalty: 0, bombPlanted: false, bombDefused: false, secondChance: true, line: LINES.secondChance, streak: s.streak, lostStreak: 0 },
              screen: "reveal",
            });
            return;
          }

          const out = betOutcome(confidence, correct);
          const exam = session.kind === "exam";
          const streak = exam ? s.streak : correct ? s.streak + 1 : 0; // Exam Day doesn't touch the streak
          const before = s.conceptState[q.conceptId];
          const after = updateState(before, { confidence, correct }, days(), now);
          const bombDefused = before.bombActive && !after.bombActive;
          const penalty = exam ? 0 : Math.min(s.chips, out.chipPenalty);
          const line = out.plantBomb
            ? LINES.certainWrong
            : bombDefused
              ? LINES.bombDefused
              : correct
                ? { guess: LINES.guessRight, pretty: LINES.prettyRight, certain: LINES.certainRight }[confidence]
                : confidence === "guess" ? LINES.guessWrong : LINES.prettyWrong;

          set({
            attempts: [...s.attempts, attempt],
            conceptState: { ...s.conceptState, [q.conceptId]: after },
            chips: s.chips - penalty,
            streak,
            reveal: { ...base, balls: exam ? 0 : out.balls, chipPenalty: penalty, bombPlanted: out.plantBomb, bombDefused, secondChance: false, line, streak, lostStreak: !exam && !correct ? s.streak : 0 },
            session: {
              ...session,
              answered: session.answered + 1,
              recent: [...session.recent, q.conceptId],
              retrying: false,
              eliminated: [],
              pendingBalls: exam ? 0 : out.balls,
              dropSeed: s.attempts.length + 1,
              streakMult: correct && !exam ? streakMultiplier(streak) : 1,
              chipsLost: session.chipsLost + penalty,
              correct: session.correct + (correct ? 1 : 0),
              bombsPlanted: out.plantBomb ? [...session.bombsPlanted, q.conceptId] : session.bombsPlanted,
              bombsDefused: bombDefused ? [...session.bombsDefused, q.conceptId] : session.bombsDefused,
            },
            screen: "reveal",
          });
        },

        continueReveal() {
          const { reveal, session } = get();
          if (!session || !reveal) return;
          if (reveal.secondChance) return set({ screen: "question", reveal: null, session: { ...session, shownAt: Date.now() } });
          if (session.kind === "exam") return next(session);
          // Shift and Defuser answers drop on the board beside the reveal; finishDrop moves on
        },

        finishDrop(raw) {
          const { session } = get();
          if (!session) return;
          const chips = Math.round(raw * (session.streakMult ?? 1));
          set((s) => ({ chips: s.chips + chips }));
          next({ ...session, pendingBalls: 0, streakMult: 1, chipsEarned: session.chipsEarned + chips });
        },

        buy(item, conceptId) {
          const s = get();
          const price = PRICES[item];
          if (s.chips < price) return;
          if (item === "secondChance") set({ chips: s.chips - price, inventory: { ...s.inventory, secondChance: s.inventory.secondChance + 1 } });
          if ((SHIFT_MODS as ShopItem[]).includes(item) && !s.inventory[item as ShiftMod])
            set({ chips: s.chips - price, inventory: { ...s.inventory, [item]: true } });
          if ((SPECIALS as ShopItem[]).includes(item) && !s.inventory.pegs.includes(item as SpecialKind))
            set({ chips: s.chips - price, inventory: { ...s.inventory, pegs: [...s.inventory.pegs, item as SpecialKind] } });
          if (item === "defuser" && conceptId && s.conceptState[conceptId]?.bombActive && !inProgress(s.session)) {
            set({ chips: s.chips - price, session: newSession("defuse", 1), reveal: null });
            get().choose(conceptId);
          }
        },

        flag(questionId) {
          const { session } = get();
          set((s) => ({ flagged: s.flagged.includes(questionId) ? s.flagged : [...s.flagged, questionId] }));
          if (session?.questionId === questionId && session.conceptId) get().choose(session.conceptId);
        },

        updateSettings(patch) {
          set((s) => ({ settings: { ...s.settings, ...patch } }));
        },

        reset() {
          set({ ...initial, settings: get().settings });
        },
      };
    },
    {
      name: "sure-thing-v1",
      // older saves predate the crazy shop and the game-show reskin
      merge: (saved, current) => {
        const s = saved as Partial<Data>;
        const inventory = { ...initial.inventory, ...s.inventory };
        inventory.pegs = inventory.pegs.map((k) => RENAMED[k as string] ?? k);
        return { ...current, ...s, inventory, settings: { ...initial.settings, ...s.settings } };
      },
    }
  )
);

/** Shared derived values for the UI. */
export function useDerived() {
  const g = useGame();
  const states = g.concepts.map((c) => g.conceptState[c.id]).filter(Boolean);
  const days = daysUntil(g.unit?.examDate ?? today());
  const ready = readiness(states, g.exam);
  return { states, days, ready, debt: 100 - ready, bombs: states.filter((s) => s.bombActive).map((s) => s.conceptId) };
}
